service: ip-check

provider:
  name: aws
  runtime: "python3.6"
  profile: admin-aws-sec
  region: us-east-1
  logRetentionInDays: 1
  environment:
    accountId: "#{AWS::AccountId}"
    region: "#{AWS::Region}"
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  auth:
    handler: handler.auth
    memorySize: 128
    events:
      - http:
          path: ip
          method: any
          cors: true
    environment:
      slack_secret: ${ssm:slack_signing_secret}

  processing:
    handler: processing.proc
    timeout: 15
    memorySize: 1024
    events:
      - sns: processing-topic
    environment:
      api_id: ${ssm:api_id}
      api_key: ${ssm:api_key}

custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
